// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import nodeosmonitor "github.com/activeeos/nodeos-monitor/pkg/nodeosmonitor"

// Monitorable is an autogenerated mock type for the Monitorable type
type Monitorable struct {
	mock.Mock
}

// Activate provides a mock function with given fields: _a0, _a1
func (_m *Monitorable) Activate(_a0 context.Context, _a1 nodeosmonitor.ProcessFailureHandler) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, nodeosmonitor.ProcessFailureHandler) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Shutdown provides a mock function with given fields: _a0
func (_m *Monitorable) Shutdown(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
