// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"

// ProcessFailureHandler is an autogenerated mock type for the ProcessFailureHandler type
type ProcessFailureHandler struct {
	mock.Mock
}

// HandleFailure provides a mock function with given fields: ctx
func (_m *ProcessFailureHandler) HandleFailure(ctx context.Context) {
	_m.Called(ctx)
}
