version: '3'
services:
  nodeos-1:
    build: .
    links:
    - etcd
    command: /opt/eosio/bin/nodeos-monitor --etcd-endpoints http://etcd:2379
  nodeos-2:
    build: .
    links:
    - etcd
    command: /opt/eosio/bin/nodeos-monitor --etcd-endpoints http://etcd:2379
  etcd:
    image: quay.io/coreos/etcd:v3.3
    command: /usr/local/bin/etcd --listen-client-urls 'http://0.0.0.0:2379' --advertise-client-urls 'http://0.0.0.0:2379'
